const SET_CAMPUSES = "SET_CAMPUSES";
const SET_STUDENTS = "SET_STUDENTS";
const SET_CAMPUS = "SET_CAMPUS";
const CREATE_CAMPUS = "CREATE_CAMPUS";
const CREATE_STUDENT = "CREATE_STUDENT";
const DESTROY_CAMPUS = "DESTROY_CAMPUS";
const DESTROY_STUDENT = "DESTROY_STUDENT";
const UPDATE_CAMPUS = "UPDATE_CAMPUS";
const UPDATE_STUDENT = "UPDATE_STUDENT";
const REGISTER_STUDENT = "REGISTER_STUDENT";
const UNREGISTER_STUDENT = "UNREGISTER_STUDENT";
const SET_ERRORS = "SET_ERRORS";
const CLEAR_ERRORS = "CLEAR_ERRORS";

const CONSTANTS = {
  SET_CAMPUS,
  SET_CAMPUSES,
  SET_STUDENTS,
  CREATE_CAMPUS,
  CREATE_STUDENT,
  DESTROY_CAMPUS,
  DESTROY_STUDENT,
  UPDATE_CAMPUS,
  UPDATE_STUDENT,
  REGISTER_STUDENT,
  UNREGISTER_STUDENT,
  SET_ERRORS,
  CLEAR_ERRORS,
};

export default CONSTANTS;
